#Importando Pandas e visualizando a tabela inicial

In [ ]:
import pandas as pd

df_economia = pd.read_csv("/content/drive/MyDrive/2024_OrcamentoDespesa.csv", sep=";", encoding="latin1")
df_economia

,EXERCÍCIO,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO SUBORDINADO,NOME ÓRGÃO SUBORDINADO,CÓDIGO UNIDADE ORÇAMENTÁRIA,NOME UNIDADE ORÇAMENTÁRIA,CÓDIGO FUNÇÃO,NOME FUNÇÃO,CÓDIGO SUBFUNÇÃO,...,NOME CATEGORIA ECONÔMICA,CÓDIGO GRUPO DE DESPESA,NOME GRUPO DE DESPESA,CÓDIGO ELEMENTO DE DESPESA,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$),% REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)
0,2024,14000,Justiça Eleitoral,14000,Justiça Eleitoral - Unidades com vínculo direto,14101,TRIBUNAL SUPERIOR ELEITORAL,2,Judiciária,61,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"0,00","0,00","23929428,72","14802059,24","0,00%"
1,2024,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"604387,85","604387,85","604387,85","579387,85","95,86%"
2,2024,20000,Presidência da República,20415,Empresa Brasil de Comunicação,20415,EMPRESA BRASIL DE COMUNICACAO,4,Administração,331,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"44681,03","44681,03","44681,03","38496,08","86,16%"
3,2024,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS DE CAPITAL,4,Investimentos,51,Obras e Instalações,"842305,76","842305,76","842305,76","842305,76","100,00%"
4,2024,20000,Presidência da República,20415,Empresa Brasil de Comunicação,20415,EMPRESA BRASIL DE COMUNICACAO,99,Reserva de contingência,999,...,RESERVA DE CONTINGENCIA,9,Reserva de Contingência,0,Não informado,"177111241,00","177111241,00","0,00","0,00","0,00%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26452,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,31,"Premiações Culturais, Artísticas, Científicas,...","1210000,00","1210000,00","1210000,00","0,00","0,00%"
26453,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS DE CAPITAL,4,Investimentos,51,Obras e Instalações,"13536,95","13536,95","13536,95","0,00","0,00%"
26454,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,0,Não informado,"-61837951,46","404999,54","0,00","0,00","0,00%"
26455,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS DE CAPITAL,4,Investimentos,0,Não informado,"-3924843,86","7205,14","0,00","0,00","0,00%"
26456,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,14,Diárias - Civil,"2807396,70","2807396,70","2771628,03","2771628,03","98,73%"

#Tirando os números de notação cientifica e deixando apenas com 2 números após o "."

In [ ]:
pd.options.display.float_format = '{:.2f}'.format

#Mudando o número da coluna para ficar mais fácil na hora de usá-la

In [ ]:
df_economia.rename(columns={'% REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)': '% REALIZADO DO ORÇAMENTO'}, inplace=True)
df_economia

,EXERCÍCIO,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO SUBORDINADO,NOME ÓRGÃO SUBORDINADO,CÓDIGO UNIDADE ORÇAMENTÁRIA,NOME UNIDADE ORÇAMENTÁRIA,CÓDIGO FUNÇÃO,NOME FUNÇÃO,CÓDIGO SUBFUNÇÃO,...,NOME CATEGORIA ECONÔMICA,CÓDIGO GRUPO DE DESPESA,NOME GRUPO DE DESPESA,CÓDIGO ELEMENTO DE DESPESA,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$),% REALIZADO DO ORÇAMENTO
0,2024,14000,Justiça Eleitoral,14000,Justiça Eleitoral - Unidades com vínculo direto,14101,TRIBUNAL SUPERIOR ELEITORAL,2,Judiciária,61,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"0,00","0,00","23929428,72","14802059,24","0,00%"
1,2024,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"604387,85","604387,85","604387,85","579387,85","95,86%"
2,2024,20000,Presidência da República,20415,Empresa Brasil de Comunicação,20415,EMPRESA BRASIL DE COMUNICACAO,4,Administração,331,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,"44681,03","44681,03","44681,03","38496,08","86,16%"
3,2024,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS DE CAPITAL,4,Investimentos,51,Obras e Instalações,"842305,76","842305,76","842305,76","842305,76","100,00%"
4,2024,20000,Presidência da República,20415,Empresa Brasil de Comunicação,20415,EMPRESA BRASIL DE COMUNICACAO,99,Reserva de contingência,999,...,RESERVA DE CONTINGENCIA,9,Reserva de Contingência,0,Não informado,"177111241,00","177111241,00","0,00","0,00","0,00%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26452,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,31,"Premiações Culturais, Artísticas, Científicas,...","1210000,00","1210000,00","1210000,00","0,00","0,00%"
26453,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS DE CAPITAL,4,Investimentos,51,Obras e Instalações,"13536,95","13536,95","13536,95","0,00","0,00%"
26454,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,0,Não informado,"-61837951,46","404999,54","0,00","0,00","0,00%"
26455,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS DE CAPITAL,4,Investimentos,0,Não informado,"-3924843,86","7205,14","0,00","0,00","0,00%"
26456,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,14,Diárias - Civil,"2807396,70","2807396,70","2771628,03","2771628,03","98,73%"

#Removendo o sufixo "%" e visualizando os tipos de dados

In [ ]:

sufixo = "%"
df_economia['% REALIZADO DO ORÇAMENTO'] = df_economia['% REALIZADO DO ORÇAMENTO'].apply(lambda x: x.removesuffix('%'))

In [ ]:
df_economia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26457 entries, 0 to 26456
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EXERCÍCIO                     26457 non-null  int64
 1   CÓDIGO ÓRGÃO SUPERIOR         26457 non-null  int64
 2   NOME ÓRGÃO SUPERIOR           26457 non-null  object
 3   CÓDIGO ÓRGÃO SUBORDINADO      26457 non-null  int64
 4   NOME ÓRGÃO SUBORDINADO        26457 non-null  object
 5   CÓDIGO UNIDADE ORÇAMENTÁRIA   26457 non-null  int64
 6   NOME UNIDADE ORÇAMENTÁRIA     26457 non-null  object
 7   CÓDIGO FUNÇÃO                 26457 non-null  int64
 8   NOME FUNÇÃO                   26457 non-null  object
 9   CÓDIGO SUBFUNÇÃO              26457 non-null  int64
 10  NOME SUBFUNÇÃO                26457 non-null  object
 11  CÓDIGO PROGRAMA ORÇAMENTÁRIO  26457 non-null  int64
 12  NOME PROGRAMA ORÇAMENTÁRIO    26457 non-null  object
 13  CÓDIGO AÇÃO                   26457 non-null  object
 14  NOME AÇÃO                     26457 non-null  object
 15  CÓDIGO CATEGORIA ECONÔMICA    26457 non-null  int64
 16  NOME CATEGORIA ECONÔMICA      26457 non-null  object
 17  CÓDIGO GRUPO DE DESPESA       26457 non-null  int64
 18  NOME GRUPO DE DESPESA         26457 non-null  object
 19  CÓDIGO ELEMENTO DE DESPESA    26457 non-null  int64
 20  NOME ELEMENTO DE DESPESA      26457 non-null  object
 21  ORÇAMENTO INICIAL (R$)        26457 non-null  object
 22  ORÇAMENTO ATUALIZADO (R$)     26457 non-null  object
 23  ORÇAMENTO EMPENHADO (R$)      26457 non-null  object
 24  ORÇAMENTO REALIZADO (R$)      26457 non-null  object
 25  % REALIZADO DO ORÇAMENTO      26457 non-null  object
dtypes: int64(10), object(16)
memory usage: 5.2+ MB

#Tranformando os dados numéricos em float e visualizando novamente os tipos dos dados

In [ ]:
df_economia["ORÇAMENTO INICIAL (R$)"] = df_economia["ORÇAMENTO INICIAL (R$)"].str.replace(",", ".").astype(float)
df_economia["ORÇAMENTO ATUALIZADO (R$)"] = df_economia["ORÇAMENTO ATUALIZADO (R$)"].str.replace(",", ".").astype(float)
df_economia["ORÇAMENTO EMPENHADO (R$)"] = df_economia["ORÇAMENTO EMPENHADO (R$)"].str.replace(",", ".").astype(float)
df_economia["ORÇAMENTO REALIZADO (R$)"] = df_economia["ORÇAMENTO REALIZADO (R$)"].str.replace(",", ".").astype(float)

In [ ]:


df_economia["% REALIZADO DO ORÇAMENTO"] = df_economia["% REALIZADO DO ORÇAMENTO"].str.replace(",", ".").astype(float)

In [ ]:
df_economia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26457 entries, 0 to 26456
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EXERCÍCIO                     26457 non-null  int64
 1   CÓDIGO ÓRGÃO SUPERIOR         26457 non-null  int64
 2   NOME ÓRGÃO SUPERIOR           26457 non-null  object
 3   CÓDIGO ÓRGÃO SUBORDINADO      26457 non-null  int64
 4   NOME ÓRGÃO SUBORDINADO        26457 non-null  object
 5   CÓDIGO UNIDADE ORÇAMENTÁRIA   26457 non-null  int64
 6   NOME UNIDADE ORÇAMENTÁRIA     26457 non-null  object
 7   CÓDIGO FUNÇÃO                 26457 non-null  int64
 8   NOME FUNÇÃO                   26457 non-null  object
 9   CÓDIGO SUBFUNÇÃO              26457 non-null  int64
 10  NOME SUBFUNÇÃO                26457 non-null  object
 11  CÓDIGO PROGRAMA ORÇAMENTÁRIO  26457 non-null  int64
 12  NOME PROGRAMA ORÇAMENTÁRIO    26457 non-null  object
 13  CÓDIGO AÇÃO                   26457 non-null  object
 14  NOME AÇÃO                     26457 non-null  object
 15  CÓDIGO CATEGORIA ECONÔMICA    26457 non-null  int64
 16  NOME CATEGORIA ECONÔMICA      26457 non-null  object
 17  CÓDIGO GRUPO DE DESPESA       26457 non-null  int64
 18  NOME GRUPO DE DESPESA         26457 non-null  object
 19  CÓDIGO ELEMENTO DE DESPESA    26457 non-null  int64
 20  NOME ELEMENTO DE DESPESA      26457 non-null  object
 21  ORÇAMENTO INICIAL (R$)        26457 non-null  float64
 22  ORÇAMENTO ATUALIZADO (R$)     26457 non-null  float64
 23  ORÇAMENTO EMPENHADO (R$)      26457 non-null  float64
 24  ORÇAMENTO REALIZADO (R$)      26457 non-null  float64
 25  % REALIZADO DO ORÇAMENTO      26457 non-null  float64
dtypes: float64(5), int64(10), object(11)
memory usage: 5.2+ MB

#Visualizando novamente a tabela

In [ ]:
df_economia

,EXERCÍCIO,CÓDIGO ÓRGÃO SUPERIOR,NOME ÓRGÃO SUPERIOR,CÓDIGO ÓRGÃO SUBORDINADO,NOME ÓRGÃO SUBORDINADO,CÓDIGO UNIDADE ORÇAMENTÁRIA,NOME UNIDADE ORÇAMENTÁRIA,CÓDIGO FUNÇÃO,NOME FUNÇÃO,CÓDIGO SUBFUNÇÃO,...,NOME CATEGORIA ECONÔMICA,CÓDIGO GRUPO DE DESPESA,NOME GRUPO DE DESPESA,CÓDIGO ELEMENTO DE DESPESA,NOME ELEMENTO DE DESPESA,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$),% REALIZADO DO ORÇAMENTO
0,2024,14000,Justiça Eleitoral,14000,Justiça Eleitoral - Unidades com vínculo direto,14101,TRIBUNAL SUPERIOR ELEITORAL,2,Judiciária,61,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,0.00,0.00,23929428.72,14802059.24,0.00
1,2024,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,604387.85,604387.85,604387.85,579387.85,95.86
2,2024,20000,Presidência da República,20415,Empresa Brasil de Comunicação,20415,EMPRESA BRASIL DE COMUNICACAO,4,Administração,331,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,39,Outros Serviços de Terceiros - Pessoa Jurídica,44681.03,44681.03,44681.03,38496.08,86.16
3,2024,20000,Presidência da República,20101,Presidência da República,20101,PRESIDENCIA DA REPUBLICA,4,Administração,122,...,DESPESAS DE CAPITAL,4,Investimentos,51,Obras e Instalações,842305.76,842305.76,842305.76,842305.76,100.00
4,2024,20000,Presidência da República,20415,Empresa Brasil de Comunicação,20415,EMPRESA BRASIL DE COMUNICACAO,99,Reserva de contingência,999,...,RESERVA DE CONTINGENCIA,9,Reserva de Contingência,0,Não informado,177111241.00,177111241.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26452,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,31,"Premiações Culturais, Artísticas, Científicas,...",1210000.00,1210000.00,1210000.00,0.00,0.00
26453,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS DE CAPITAL,4,Investimentos,51,Obras e Instalações,13536.95,13536.95,13536.95,0.00,0.00
26454,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,0,Não informado,-61837951.46,404999.54,0.00,0.00,0.00
26455,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,423,...,DESPESAS DE CAPITAL,4,Investimentos,0,Não informado,-3924843.86,7205.14,0.00,0.00,0.00
26456,2024,84000,Ministério dos Povos Indígenas,30202,Fundação Nacional dos Povos Indígenas,84201,FUNDACAO NACIONAL DOS POVOS INDIGENAS,14,Direitos da cidadania,122,...,DESPESAS CORRENTES,3,Outras Despesas Correntes,14,Diárias - Civil,2807396.70,2807396.70,2771628.03,2771628.03,98.73

#Vendo os 10 Órgãos Superiores com maior Orçamento Realizado

In [ ]:
maior_10_sup = df_economia[['NOME ÓRGÃO SUPERIOR', 'ORÇAMENTO REALIZADO (R$)']].groupby('NOME ÓRGÃO SUPERIOR').sum()
maior_10_sup.sort_values(by='ORÇAMENTO REALIZADO (R$)', ascending=False).head(10)

                                                    ORÇAMENTO REALIZADO (R$)
NOME ÓRGÃO SUPERIOR
Ministério da Fazenda                                       2491999707319.89
Ministério da Previdência Social                             874220908828.93
Ministério do Desenvolvimento e Assistência Soc...           278162795151.43
Ministério da Saúde                                          204072502296.08
Ministério da Educação                                       172895482206.85
Ministério da Defesa                                         112254150219.43
Ministério do Trabalho e Emprego                             111573721782.84
Ministério de Minas e Energia                                 65616947101.35
Ministério da Integração e do Desenvolvimento R...            32946944006.96
Ministério das Cidades                                        21361439396.24

#Mostrando a Variação Absoluta e Variação Percentual

In [ ]:
vari_absper = df_economia[['NOME ÓRGÃO SUBORDINADO', 'ORÇAMENTO REALIZADO (R$)','ORÇAMENTO INICIAL (R$)']].groupby('NOME ÓRGÃO SUBORDINADO').sum()
vari_absper["Variação Absoluta"] = vari_absper["ORÇAMENTO REALIZADO (R$)"] - vari_absper["ORÇAMENTO INICIAL (R$)"]
vari_absper["Variação Percentual"] = vari_absper["Variação Absoluta"] / vari_absper["ORÇAMENTO INICIAL (R$)"] * 100
vari_absper["Variação Percentual"] = vari_absper["Variação Percentual"].round(2)
display(vari_absper)

,ORÇAMENTO REALIZADO (R$),ORÇAMENTO INICIAL (R$),Variação Absoluta,Variação Percentual
NOME ÓRGÃO SUBORDINADO,,,,
Advocacia-Geral da União - Unidades com vínculo direto,4069274832.25,4412331203.00,-343056370.75,-7.77
Agência Espacial Brasileira,75402075.04,148331339.00,-72929263.96,-49.17
Agência Nacional de Aviação Civil,494598543.38,888498345.00,-393899801.62,-44.33
Agência Nacional de Energia Elétrica,5543895631.71,6200595477.00,-656699845.29,-10.59
Agência Nacional de Mineração,5848394357.72,6886143156.00,-1037748798.28,-15.07
...,...,...,...,...
Universidade Federal do Triângulo Mineiro,544067109.96,602760781.00,-58693671.04,-9.74
Universidade Federal dos Vales do Jequitinhonha e Mucuri,324455186.32,356658823.00,-32203636.68,-9.03
Universidade Tecnológica Federal do Paraná,1094927459.02,1247027698.00,-152100238.98,-12.20
Universidade da Integração Internacional da Lusofonia Afro-Brasileira,172551293.35,188434718.00,-15883424.65,-8.43
"VALEC Engenharia, Construções e Ferrovias S.A.",232274584.23,892551384.00,-660276799.77,-73.98

#Mostrando ranking de eficiência orçamentária

In [ ]:
ran_efi = df_economia[['NOME UNIDADE ORÇAMENTÁRIA','% REALIZADO DO ORÇAMENTO']].groupby('NOME UNIDADE ORÇAMENTÁRIA').sum()
ran_efi.sort_values(by='% REALIZADO DO ORÇAMENTO', ascending=False)

                                              % REALIZADO DO ORÇAMENTO
NOME UNIDADE ORÇAMENTÁRIA
FUNDO NACIONAL DE SAUDE                                       34277.53
COMANDO DO EXERCITO                                           26314.35
MINIST. DA CIENCIA, TECNOLOGIA E INOVOVACAO                   24067.62
MINISTERIO DA DEFESA                                          20934.83
FUNDACAO OSWALDO CRUZ                                         18784.07
...                                                                ...
FUNDO ESPECIAL DE FINANCIAMENTO DE CAMPANHA                       0.00
ENCARGOS FINANC.DA UNIAO-SENTENCAS JUDICIAIS                      0.00
RESERVA DE CONTINGENCIA                                           0.00
TRIBUNAL SUPERIOR ELEITORAL                                       0.00
COMPANHIA NACIONAL DE ABASTECIMENTO                          -18262.89

[338 rows x 1 columns]

#Mosrando a despesa média de cada "Nome Função" e quais estão acima ou abaixo da Média

In [ ]:
des_med = df_economia[['NOME FUNÇÃO','ORÇAMENTO REALIZADO (R$)']].groupby('NOME FUNÇÃO').mean()
des_med.sort_values(by="ORÇAMENTO REALIZADO (R$)", ascending=False)
soma = df_economia["ORÇAMENTO REALIZADO (R$)"].sum()
media = soma  / 26457
des_med["Acima da média"] = des_med["ORÇAMENTO REALIZADO (R$)"] > media
des_med["Acima da média"] = des_med["Acima da média"].replace(True, "Acima da Média")
des_med["Acima da média"] = des_med["Acima da média"].replace(False, "Abaixo da Média")
des_med

                         ORÇAMENTO REALIZADO (R$)   Acima da média
NOME FUNÇÃO
Administração                         14280301.66  Abaixo da Média
Agricultura                           25583227.97  Abaixo da Média
Assistência social                   909050981.31   Acima da Média
Ciência e Tecnologia                  14541393.86  Abaixo da Média
Comunicações                           9801513.58  Abaixo da Média
Comércio e serviços                   20260824.78  Abaixo da Média
Cultura                                3279080.33  Abaixo da Média
Defesa nacional                       41794808.05  Abaixo da Média
Desporto e lazer                       2223211.19  Abaixo da Média
Direitos da cidadania                  1562273.09  Abaixo da Média
Educação                              13694324.81  Abaixo da Média
Encargos especiais                  1679131749.36   Acima da Média
Energia                                2978189.75  Abaixo da Média
Essencial à justiça                   24008102.39  Abaixo da Média
Gestão ambiental                      14839417.77  Abaixo da Média
Habitação                               642995.64  Abaixo da Média
Indústria                              4126432.79  Abaixo da Média
Judiciária                            14802059.24  Abaixo da Média
Organização agrária                    6711542.97  Abaixo da Média
Previdência social                   765503816.89   Acima da Média
Relações exteriores                   20570849.48  Abaixo da Média
Reserva de contingência                      0.00  Abaixo da Média
Saneamento                             5141488.53  Abaixo da Média
Saúde                                153060689.30  Abaixo da Média
Segurança pública                     37568261.83  Abaixo da Média
Trabalho                             410927487.47   Acima da Média
Transporte                            15013320.18  Abaixo da Média
Urbanismo                              5144425.01  Abaixo da Média

#Mostrando qual categoria econômica com mais Orçamento Realizado e a porcentagem

In [ ]:
maior_parte = df_economia[["NOME CATEGORIA ECONÔMICA","ORÇAMENTO REALIZADO (R$)"]].groupby("NOME CATEGORIA ECONÔMICA").sum()
total = maior_parte["ORÇAMENTO REALIZADO (R$)"].sum()
maior_parte["Porcentagem"] = maior_parte["ORÇAMENTO REALIZADO (R$)"] / total * 100
maior_parte

                          ORÇAMENTO REALIZADO (R$)  Porcentagem
NOME CATEGORIA ECONÔMICA
DESPESAS CORRENTES                2683299823620.14        59.74
DESPESAS DE CAPITAL               1808087265496.21        40.26
RESERVA DE CONTINGENCIA                       0.00         0.00

#Mostrando a proporção entre o realizado e o realizado total em % de cada Órgão Superior

In [ ]:
pro_real = df_economia[["NOME ÓRGÃO SUPERIOR","ORÇAMENTO REALIZADO (R$)", "% REALIZADO DO ORÇAMENTO"]].groupby("NOME ÓRGÃO SUPERIOR").sum()
pro_real["Proporção"] = pro_real["ORÇAMENTO REALIZADO (R$)"] / pro_real["% REALIZADO DO ORÇAMENTO"]
pro_real["Proporção"] = pro_real["Proporção"] / 100
pro_real.sort_values(by="Proporção", ascending=False, inplace=True)
pro_real["Proporção"] = pro_real["Proporção"].replace(float('inf'), 0)
pro_real

,ORÇAMENTO REALIZADO (R$),% REALIZADO DO ORÇAMENTO,Proporção
NOME ÓRGÃO SUPERIOR,,,
Justiça Eleitoral,14802059.24,0.00,0.00
Ministério da Fazenda,2491999707319.89,35628.70,699436.05
Ministério da Previdência Social,874220908828.93,15766.04,554496.19
"Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome",278162795151.43,13625.19,204153.33
Ministério do Trabalho e Emprego,111573721782.84,14213.33,78499.35
Ministério da Saúde,204072502296.08,70396.28,28989.10
Ministério das Cidades,21361439396.24,14364.17,14871.34
Ministério de Minas e Energia,65616947101.35,49200.64,13336.60
Advocacia-Geral da União,4069274832.25,3555.54,11444.89
Ministério da Defesa,112254150219.43,124297.62,9031.08
Ministério da Integração e do Desenvolvimento Regional,32946944006.96,47645.80,6914.97
Banco Central do Brasil - Orçamento Fiscal e Seguridade Social,3754747970.63,5706.38,6579.91
Ministério da Gestão e da Inovação em Serviços Públicos,12010547973.10,18937.33,6342.26
Ministério da Justiça e Segurança Pública,17127887816.56,28036.09,6109.23
Ministério da Agricultura e Pecuária,13869660626.33,24729.25,5608.61
Ministério dos Transportes,13880750029.33,26154.98,5307.12
"Ministério do Empreendedorismo, da Microempresa e da Empresa de Pequeno Porte",906048920.19,1962.20,4617.52
Ministério do Meio Ambiente e Mudança do Clima,13570006585.02,34354.30,3950.02
Ministério das Relações Exteriores,5163323392.27,17020.11,3033.66
"Ministério da Ciência, Tecnologia e Inovação",16246118029.37,54002.48,3008.40
Controladoria-Geral da União,1211848868.71,4107.73,2950.17
Ministério da Educação,172895482206.85,672073.24,2572.57
Ministério do Planejamento e Orçamento,5033317079.40,20211.86,2490.28
Ministério de Portos e Aeroportos,3179409653.60,13542.95,2347.65
Ministério da Pesca e Aquicultura,1106283864.88,4894.30,2260.35
Ministério do Turismo,1064853195.97,4921.30,2163.76
Ministério das Comunicações,2420093578.06,13544.81,1786.73
Presidência da República,2334971826.44,21686.91,1076.67
Ministério dos Povos Indígenas,879059559.20,8834.10,995.08
"Ministério do Desenvolvimento, Indústria, Comércio e Serviços",1680349449.40,17740.94,947.16
Ministério da Cultura,2241471447.83,31911.32,702.41
Ministério do Esporte,301285959.97,4842.99,622.11
Ministério dos Direitos Humanos e Cidadania,274951809.07,7274.44,377.97
Ministério das Mulheres,76602935.87,3282.97,233.33
Ministério da Igualdade Racial,114084308.96,5567.40,204.91
Ministério do Desenvolvimento Agrário e Agricultura Familiar,3750739034.70,-170.77,-219636.88

#Vendo qual Órgão Superior teve grande aumento ou não

In [ ]:
cor_ou_exp = df_economia[["NOME ÓRGÃO SUPERIOR","ORÇAMENTO INICIAL (R$)","ORÇAMENTO ATUALIZADO (R$)"]].groupby("NOME ÓRGÃO SUPERIOR").sum()
cor_ou_exp["Diferença"] = cor_ou_exp["ORÇAMENTO ATUALIZADO (R$)"] - cor_ou_exp["ORÇAMENTO INICIAL (R$)"]
diferenca_grande = 80000000
cor_ou_exp["Aumento ou não"] = cor_ou_exp["Diferença"] > diferenca_grande
cor_ou_exp["Aumento ou não"] = cor_ou_exp["Aumento ou não"].replace(True, "Grande Aumento")
cor_ou_exp["Aumento ou não"] = cor_ou_exp["Aumento ou não"].replace(False, "Pouco aumento ou diminuiu")
cor_ou_exp

,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),Diferença,Aumento ou não
NOME ÓRGÃO SUPERIOR,,,,
Advocacia-Geral da União,4412331203.00,4565215105.00,152883902.00,Grande Aumento
Banco Central do Brasil - Orçamento Fiscal e Seguridade Social,4140469716.00,4125219801.00,-15249915.00,Pouco aumento ou diminuiu
Controladoria-Geral da União,1379087376.00,1387617642.00,8530266.00,Pouco aumento ou diminuiu
Justiça Eleitoral,0.00,0.00,0.00,Pouco aumento ou diminuiu
Ministério da Agricultura e Pecuária,18265165899.82,18664945509.82,399779610.00,Grande Aumento
"Ministério da Ciência, Tecnologia e Inovação",19170845587.00,18893436345.00,-277409242.00,Pouco aumento ou diminuiu
Ministério da Cultura,6995221667.99,3915073541.99,-3080148126.00,Pouco aumento ou diminuiu
Ministério da Defesa,126679867264.87,127175793117.87,495925853.00,Grande Aumento
Ministério da Educação,208019219940.00,211120005077.00,3100785137.00,Grande Aumento
Ministério da Fazenda,3051928579000.98,3091819452546.98,39890873546.00,Grande Aumento
Ministério da Gestão e da Inovação em Serviços Públicos,13836296477.00,14432217802.00,595921325.00,Grande Aumento
Ministério da Igualdade Racial,180433909.00,162954503.00,-17479406.00,Pouco aumento ou diminuiu
Ministério da Integração e do Desenvolvimento Regional,38388652675.00,45224414784.00,6835762109.00,Grande Aumento
Ministério da Justiça e Segurança Pública,21960378291.00,22143160855.00,182782564.00,Grande Aumento
Ministério da Pesca e Aquicultura,350731363.00,1253882789.00,903151426.00,Grande Aumento
Ministério da Previdência Social,929797250849.00,958885592406.00,29088341557.00,Grande Aumento
Ministério da Saúde,232058342894.00,233221902317.00,1163559423.00,Grande Aumento
Ministério das Cidades,22049055984.00,26462899021.00,4413843037.00,Grande Aumento
Ministério das Comunicações,3413772164.00,3610278606.00,196506442.00,Grande Aumento
Ministério das Mulheres,480620937.00,317681213.00,-162939724.00,Pouco aumento ou diminuiu
Ministério das Relações Exteriores,4582917477.97,5174506539.97,591589062.00,Grande Aumento
Ministério de Minas e Energia,83561147417.00,86280302365.00,2719154948.00,Grande Aumento
Ministério de Portos e Aeroportos,13197195060.00,16873258911.00,3676063851.00,Grande Aumento
Ministério do Desenvolvimento Agrário e Agricultura Familiar,6135704849.99,8336329765.99,2200624916.00,Grande Aumento
"Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome",281871949589.00,290409084753.00,8537135164.00,Grande Aumento
"Ministério do Desenvolvimento, Indústria, Comércio e Serviços",2944507712.00,2953357659.00,8849947.00,Pouco aumento ou diminuiu
"Ministério do Empreendedorismo, da Microempresa e da Empresa de Pequeno Porte",0.00,2113354474.00,2113354474.00,Grande Aumento
Ministério do Esporte,2294799857.00,2264550775.00,-30249082.00,Pouco aumento ou diminuiu
Ministério do Meio Ambiente e Mudança do Clima,14106424106.00,17899923662.00,3793499556.00,Grande Aumento
Ministério do Planejamento e Orçamento,15427779581.00,6433446338.00,-8994333243.00,Pouco aumento ou diminuiu
Ministério do Trabalho e Emprego,110264194198.00,116369223158.00,6105028960.00,Grande Aumento
Ministério do Turismo,2907418326.00,3114242385.00,206824059.00,Grande Aumento
Ministério dos Direitos Humanos e Cidadania,502579667.00,500994961.00,-1584706.00,Pouco aumento ou diminuiu
Ministério dos Povos Indígenas,849776401.00,1393064608.00,543288207.00,Grande Aumento
Ministério dos Transportes,56389317644.00,54763937002.00,-1625380642.00,Pouco aumento ou diminuiu
Presidência da República,25270184781.00,25309221702.00,39036921.00,Pouco aumento ou diminuiu

#Mostrando qual Unidade Orçamentária utilizou mais ou menos de 50% do Orçamento Atualizado

In [ ]:
menos_50_uti = df_economia[["NOME UNIDADE ORÇAMENTÁRIA","ORÇAMENTO ATUALIZADO (R$)","ORÇAMENTO REALIZADO (R$)"]].groupby("NOME UNIDADE ORÇAMENTÁRIA").sum()
Metade = menos_50_uti["ORÇAMENTO ATUALIZADO (R$)"] / 2
menos_50_uti["50% Utilizado"] = Metade >= menos_50_uti["ORÇAMENTO REALIZADO (R$)"]
menos_50_uti["50% Utilizado"] = menos_50_uti["50% Utilizado"].replace(True, "Menos de 50% Utilizado")
menos_50_uti["50% Utilizado"] = menos_50_uti["50% Utilizado"].replace(False, "Mais de ou igual à 50% Utilizado")
menos_50_uti

,ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO REALIZADO (R$),50% Utilizado
NOME UNIDADE ORÇAMENTÁRIA,,,
ADVOCACIA-GERAL DA UNIAO - AGU,4565215105.00,4069274832.25,Mais de ou igual à 50% Utilizado
AGENCIA BRASILEIRA DE INTELIGENCIA - ABIN,783901899.00,703954728.53,Mais de ou igual à 50% Utilizado
AGENCIA ESPACIAL BRASILEIRA - AEB,135631669.00,75402075.04,Mais de ou igual à 50% Utilizado
AGENCIA NAC. DE TRANSPORTES AQUAVIARIOS-ANTAQ,286256094.00,158704632.98,Mais de ou igual à 50% Utilizado
AGENCIA NAC. DE TRANSPORTES TERRESTRES - ANTT,35780299784.00,487713562.71,Menos de 50% Utilizado
...,...,...,...
UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO,747154183.00,665975009.70,Mais de ou igual à 50% Utilizado
UNIVERSIDADE FEDERAL RURAL DO RIO DE JANEIRO,879450774.00,751761396.40,Mais de ou igual à 50% Utilizado
UNIVERSIDADE FEDERAL RURAL DO SEMI-ARIDO,398052835.00,354690704.09,Mais de ou igual à 50% Utilizado
UNIVERSIDADE TECNOLOGICA FEDERAL DO PARANA,1287928469.00,1094927459.02,Mais de ou igual à 50% Utilizado
"VALEC-ENGENHARIA, CONSTRUCOES E FERROVIAS S/A",560137823.00,232274584.23,Menos de 50% Utilizado

#Correlação entre grupos de despesas

In [ ]:
relacao_entre_despesas = df_economia[["ORÇAMENTO INICIAL (R$)", "ORÇAMENTO ATUALIZADO (R$)", "ORÇAMENTO EMPENHADO (R$)", "ORÇAMENTO REALIZADO (R$)"]].corr()
relacao_entre_despesas

,ORÇAMENTO INICIAL (R$),ORÇAMENTO ATUALIZADO (R$),ORÇAMENTO EMPENHADO (R$),ORÇAMENTO REALIZADO (R$)
ORÇAMENTO INICIAL (R$),1.00,1.00,0.99,0.99
ORÇAMENTO ATUALIZADO (R$),1.00,1.00,0.99,1.00
ORÇAMENTO EMPENHADO (R$),0.99,0.99,1.00,1.00
ORÇAMENTO REALIZADO (R$),0.99,1.00,1.00,1.00